### ISSUE TITLE
Release file format is Mach-O (OSX)

### ISSUE THREAD

**Issue by sumppen** [ollytom/check_wildflyfree#4]
The check_wildflyfree binary file is compiled as an Mac OS executable and does not work on linux

`#` file check_wildflyfree
check_wildflyfree: Mach-O 64-bit x86_64 executable
`#` ./check_wildflyfree
-bash: ./check_wildflyfree: cannot execute binary file: Exec format error
`#` uname -m
x86_64

I would compile the source myself, but the required go module (wildfly) is no longer available at https://git.sr.ht/~otl/wildfly

**Comment by ollytom** [comment]
Hey there! I didn't know this was used by anyone, sorry!
I'll restore this without that module dependency. Then I can upload binaries.

**Comment by ollytom** [comment]
Hey @sumppen I've just fixed the build and uploaded a Linux binary for arch amd64 to 
https://github.com/ollytom/check_wildflyfree/releases/tag/v0.2.0
Let me know how that goes for you :)

Cheers from Australia!

**Comment by sumppen** [comment]
Hi @ollytom
The build still doesn't work with linux (seems to be OpenBSD?) 
`# file check_wildflyfree.orig`
check_wildflyfree.orig: ELF 64-bit LSB executable, x86-64, version 1 (OpenBSD), dynamically linked, interpreter /usr/libexec/ld.so, for OpenBSD, with debug_info, not stripped
`# ./check_wildflyfree.orig`
-bash: ./check_wildflyfree.orig: No such file or directory
However, I was now able to build my own which does work (after learning how to import an external module in GO)
`# file check_wildflyfree`
check_wildflyfree: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, with debug_info, not stripped
`# ./check_wildflyfree -h localhost:9990 -u icinga -p password_redacted`
4% of heap memory used (2030194672 of 9544663040 bytes) | heap_used_percent=4, heap_used_bytes=2030194672
Thank you for a prompt response
